disabled_rules: # 执行时排除掉的规则
  - trailing_whitespace
  - type_name
  - line_length
  - identifier_name
  - large_tuple
opt_in_rules: # 一些规则仅仅是可选的
  - empty_count
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_string
  - fatal_error_message
  - legacy_random
  - let_var_whitespace
  - yoda_condition # 尤达

  # 可以通过执行如下指令来查找所有可用的规则:
  # swiftlint rules
included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods
  - R.generated.swift

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式

force_try:
  severity: warning # 显式

type_body_length:
  warning: 300 
  error: 400

file_length:
  warning: 1000
  error: 1200

vertical_whitespace:
  max_empty_lines: 2

reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)